apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 381492134996.dkr.ecr.us-east-1.amazonaws.com/backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "database-1.cnq48sio8gw0.us-east-1.rds.amazonaws.com"  # Replace with actual RDS endpoint
            - name: DB_USER
              value: "admin"  # Replace with actual DB username
            - name: DB_PASS
              value: "12345678"  # Replace with actual DB password
            - name: DB_NAME
              value: "mydb" 
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
